accepted = [
    "Apache-2.0",
    "MIT",
    "ISC",
    "BSD-3-Clause",
    "MPL-2.0",
]

targets = [
    "x86_64-unknown-linux-gnu",
    "x86_64-unknown-linux-musl",
]

ignore-build-dependencies = true
ignore-dev-dependencies = true
